seed: 2024
gpu: 0
train_gt: /path/to/DF2K_train_HR
output_dir: runs/blind
width: 144
batch_size: 16
num_workers: 2
crop_size: 128
epochs: 2000
stage1_epochs: 1000
qf_min: 10
qf_max: 70
qf_step: 10
subsampling: "444"
learning_rate: 0.0002
min_learning_rate: 0.00002
fft_weight: 0.01
gradient_weight: 0.01
save_every: 10
